### ISSUE TITLE
Misleading README

### ISSUE THREAD

**Issue by Zelakolase** [hegzploit/A-Wise-Cat-Once-Said#1]
First: Scientifically speaking, cats are not intelligent enough (Blame it on evolution) to be wise. Humans can be dangerously mislead.

Second : 'README.md' says in 'requirements' section that the code was built in C++, while '.c' extension was used. Therefore, there's a non-negligible chance that the code is built in [C language](https://en.wikipedia.org/wiki/C_(programming_language)). Compilation process can fail due to misleading instructions.

Therefore, I demand the modification (or removal if necessary) for this repository, as it misleads both the public and the compilers (referring to [people who compile](https://en.wikipedia.org/wiki/Programmer), not [compilers](https://en.wikipedia.org/wiki/Compiler)).

**Comment by hegzploit** [comment]
> Scientifically speaking, cats are not intelligent enough

Tool is advertised to 'quote a cat's wisdom', however, one can quote his own wisdom and just blame the cat, perfect misuse of this tool.

> 'README.md' says in 'requirements' section that the code was built in C++

Was intending to write it in C++ but thought it was overkill, g++ will compile this just fine though, [also corrected](https://github.com/hegzploit/A-Wise-Cat-Once-Said/commit/6383cf0f03d15076ca8d2c4c30a0550a8024c488).

Thanks for the issue, next time please make a pull request and I will roll it into production.

**Comment by Zelakolase** [comment]
Greetings,

Thanks for the modification, I just want to note that being biased for cats is a racist reference against other animals (e.g. dogs). So please add other animals in the next release.
